### ISSUE TITLE
Use ssh keys rather than passwords to login

### ISSUE THREAD

**Issue by osiloke** [rsaikali/django-skwissh#12]
It would be nice to add ssh keys as an auth method since some server admins may find that more secure

**Comment by rsaikali** [comment]
Hi,

It seems you can already use SSH keys as described in this issue :
https://github.com/rsaikali/django-skwissh/issues/2#issuecomment-8035402

Please let me know if it you have any problem...

Thanks.

Roland.

**Comment by osiloke** [comment]
I stand corrected sir, forgot you built on fabric duh.
Thank you
