### ISSUE TITLE
Better SSH authentication management

### ISSUE THREAD

**Issue by rsaikali** [rsaikali/django-skwissh#2]
To avoid storing passwords in database, SSH authentication should be managed differently.

Use of SSH [keyfiles](http://docs.fabfile.org/en/1.4.3/usage/env.html#key-filename) should be studied.

**Comment by rsaikali** [comment]
v0.0.5 enhancement : use fabric local() command if server ip is detected as 127.0.0.1

Not a big deal, but better than nothing : faster execution (no SSH) no need for username/password.

**Comment by mbi** [comment]
It seems to me this is could simply be covered by documentation, i.e. 
- leave the password field empty
- if needed, create a ssh key (ssh-keygen)
- copy the key to every server being monitored (ssh-copy-id)

This already works flawlessly.

**Comment by rsaikali** [comment]
That's what I wanted to try (need time !!)
I knew this was the default Fabric behaviour, but I wondered if it worked in a Django environment (don't know why it shouldn't).

Thanks for testing that... 

"This already works flawlessly."
So I close this ticket...

**Comment by rsaikali** [comment]
"It seems to me this is could simply be covered by documentation"

Correct ! Need to review the docs...
