### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by COLABORATI** [rsaikali/django-skwissh#27]
website is down. What about using some monitoring tool :) ?

**Comment by rsaikali** [comment]
Yes, sorry for that.
Skwissh is now 2 or 3 years old.. domain name has not been renewed.
Code has not been maintained (Django 1.3 or 1.4... as we're now in Django 1.8).

Aimed to be a 'light' monitoring tool, without any 'agent' on monitored machines.
I've now switched to more robust tools, Collectd and friends, and Grafana for UI.

**Comment by COLABORATI** [comment]
If it is dead, it would be ok to write that on top of the readme, just to help disoriented people like me, thanks!
