### ISSUE TITLE
Ability to set alarms

### ISSUE THREAD

**Issue by rsaikali** [rsaikali/django-skwissh#4]
Ability to set alarms for a sensor, depending on its value.

Alarm could be specified as :
"If this sensor for this server is (under/above/equal to) this value then trigger an alert.".

Alerts could be :
- An email (to one/multiple users, registered for this alarm).
- A twitter post (can be a private Twitter account if you don't want the whole world to know your Skwissh alerts).
- Any other social network post (FB ? G+ ? ...)
- Anything else ? (Ability to launch a dedicated shell file...).

This is a primary analysis... let's discuss about this if you want...

**Comment by n3storm** [comment]
Alert could also be a webhook, so we can trigger a more complicated mechanism, like, in certain conditions restart daemon.

input_field: http://anotherurl/complicatedmechanism?api_key=564654654654&service=apache&status=death&measure=stop_and_start

Email and webhook should be first implemented in my opinion. IMHO, we will never notifiy to a Social Network...

Cheers and thanks for your great work on skwissh, I will try to help you as soon as I have some time a weekend  :)

**Comment by rsaikali** [comment]
Thank you for your feedback.

In my opinion, the first system to be implemented should be 'Launch a script file' (so inside the script we could do almost anything we want...).
We should keep in mind to launch specific command directly from the GUI, but it could come in future versions.

I also don't have time to work on it currently, sorry, but I keep in mind this enhancement.

Thanks again.

**Comment by n3storm** [comment]
mmm, what about creating a generic input field labelled URI and use something like file:///local, ssh:///fuu or http:///mydomain? In each case we can make it trigger a local script as you suggest, a remote script (both using fabric) and making a request using python-request for the later.

Also, we can leave the system open for more protocols or URI handlers, like mailto:/// will send an email.

See http://es.wikipedia.org/wiki/Uniform_Resource_Identifier

So alarm will be "If this sensor for this server is (under/above/equal to) this value then trigger an alert to this URI(s)"

if SENSOR >=< VALUE then (URI1://MESSAGE1, URI2://MESSAGE2, ...)

I will help with this if we reach an agreement and manage to put everything together :)

Cheers (and thanks for your software)

**Comment by sean-m** [comment]
I like the 'run a script' idea. That way you could have a process that may watch for a few measures of the sensor and then notify if things don't normalize. Nothing's more annoying than getting thousands of false positives thrown into your inbox.
