### ISSUE TITLE
Ability to order sensors

### ISSUE THREAD

**Issue by rsaikali** [rsaikali/django-skwissh#5]
User may want to order its sensors on a server page.

For example, user may want to have first the 'CPU' sensor, then 'memory' items, then the 'disk usage' stuff and finally the 'load avg' info.

Currently sensors are ordered alphabetically.
They should be ordered by an 'order' field, depending on the server they're attached.

**Comment by n3storm** [comment]
Hi there.

I would like to be able to order sensors and also it would be great a mini mode for sensors. For example, I want to have three ordered sensors for "lamp", "mail", "fuu", they are mini mode, they are just either red or or green and all of them fit in one row, one third each sensor.

Settings will be like: {'lamp':{'order':3,'width':'third'},'mail':{'order':1,'width':'third'},'fuu':{'order':2,'width':'third'},}

**Comment by rsaikali** [comment]
I love the 'mini mode' idea, this should be great to have sensors in less space ('pie charts' occupy only a few width compared to the page width...).

Thanks for your reply, and same comment than the 'alerts' issue : don't have a lot of time, but I don't give up... :-)
