### ISSUE TITLE
TemplateDoesNotExist skwissh/server_form.html while updating a server configuration

### ISSUE THREAD

**Issue by mbi** [rsaikali/django-skwissh#7]
Running v0.0.5 installed form pip:
- Display graphs for a server
- From the drop-down menu, "Edit this server…"
- Forget to enter the password, Click "save"

**Comment by rsaikali** [comment]
I've changed the password field as 'not required' in next 0.0.6 : 'localhost' or '127.0.0.1' will not use SSH anymore, but local() fabric execution (doesn't need password) and server IP is no longer an IPField but a simple CharField (support for hostnames).

But you're right, forms errors (in general) redirect to a bad page... need to fix all of them (server form, server group form and sensor form).

**Comment by rsaikali** [comment]
v0.0.6 : Should be OK now...
